name: deploy production

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    env:
      APP_ENV: production
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install

      - run: |
          expo publish --release-channel prod-v2.0
          echo "DEPLOY_STATE=successful" >> $GITHUB_ENV

      - name: Failed Deployment
        if: failure()
        run: echo "DEPLOY_STATE=failed" >> $GITHUB_ENV

      - name: Confirm Deploy State
        if: always()
        run: |
          echo "DEPLOY_STATE: ${{ env.DEPLOY_STATE }}"
